"""add pricing tables with timestamps

Revision ID: 1343fa765ac1
Revises: 1dac18177299
Create Date: 2025-11-14 20:31:58.697241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1343fa765ac1'
down_revision: Union[str, None] = '1dac18177299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycle_discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_name')
    )
    op.create_table('calculator_addon_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('addon_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculator_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('storage', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosting_plan_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('storage', sa.Integer(), nullable=False),
    sa.Column('bandwidth', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_quarterly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_semiannually', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_annually', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_biennially', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_triennially', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('processor_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_type_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('use_case_description', sa.Text(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_type_metadata')
    op.drop_table('hosting_plan_configurations')
    op.drop_table('calculator_configurations')
    op.drop_table('calculator_addon_pricing')
    op.drop_table('billing_cycle_discounts')
    # ### end Alembic commands ###
