"""Initial database setup - 13 tables for BIDUA Hosting Platform

Revision ID: 2ef3b7587435
Revises: 
Create Date: 2025-11-14 17:54:28.076352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef3b7587435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosting_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('bandwidth_gb', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quarterly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('biennial_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('triennial_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_active_featured', 'hosting_plans', ['is_active', 'is_featured'], unique=False)
    op.create_index('idx_plan_created', 'hosting_plans', ['created_at'], unique=False)
    op.create_index('idx_plan_price', 'hosting_plans', ['monthly_price'], unique=False)
    op.create_index('idx_plan_type_status', 'hosting_plans', ['plan_type', 'is_active'], unique=False)
    op.create_table('referral_commission_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'SERVER', name='paymenttype'), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commission_rate_active', 'referral_commission_rates', ['level', 'payment_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_referral_commission_rates_level'), 'referral_commission_rates', ['level'], unique=False)
    op.create_index(op.f('ix_referral_commission_rates_payment_type'), 'referral_commission_rates', ['payment_type'], unique=False)
    op.create_table('users_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('referral_level_1', sa.Integer(), nullable=True),
    sa.Column('referral_level_2', sa.Integer(), nullable=True),
    sa.Column('referral_level_3', sa.Integer(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('l1_referrals', sa.Integer(), nullable=True),
    sa.Column('l2_referrals', sa.Integer(), nullable=True),
    sa.Column('l3_referrals', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_withdrawn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('activation_type', sa.String(length=20), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referral_level_1'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['referral_level_2'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['referral_level_3'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['referred_by'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_balance_status', 'users_profiles', ['available_balance', 'account_status'], unique=False)
    op.create_index('idx_user_created_at', 'users_profiles', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users_profiles', ['email'], unique=False)
    op.create_index('idx_user_referral_code', 'users_profiles', ['referral_code'], unique=False)
    op.create_index('idx_user_referred_by', 'users_profiles', ['referred_by'], unique=False)
    op.create_index('idx_user_status_role', 'users_profiles', ['account_status', 'role'], unique=False)
    op.create_index('idx_user_subscription', 'users_profiles', ['subscription_status', 'subscription_end'], unique=False)
    op.create_index(op.f('ix_users_profiles_email'), 'users_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_users_profiles_referral_code'), 'users_profiles', ['referral_code'], unique=True)
    op.create_table('billing_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('server_alerts', sa.Boolean(), nullable=True),
    sa.Column('billing_alerts', sa.Boolean(), nullable=True),
    sa.Column('maintenance_alerts', sa.Boolean(), nullable=True),
    sa.Column('marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('activation_type', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('server_details', sa.JSON(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['hosting_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_billing_cycle', 'orders', ['billing_cycle'], unique=False)
    op.create_index('idx_order_comprehensive', 'orders', ['user_id', 'order_status', 'payment_status', 'created_at'], unique=False)
    op.create_index('idx_order_created_date', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_order_payment_date', 'orders', ['payment_date'], unique=False)
    op.create_index('idx_order_payment_status_date', 'orders', ['payment_status', 'created_at'], unique=False)
    op.create_index('idx_order_plan', 'orders', ['plan_id'], unique=False)
    op.create_index('idx_order_service_dates', 'orders', ['service_start_date', 'service_end_date'], unique=False)
    op.create_index('idx_order_status_payment', 'orders', ['order_status', 'payment_status'], unique=False)
    op.create_index('idx_order_user_payment_status', 'orders', ['user_id', 'payment_status'], unique=False)
    op.create_index('idx_order_user_status', 'orders', ['user_id', 'order_status'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_plan_id'), 'orders', ['plan_id'], unique=False)
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('card_holder_name', sa.String(length=255), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('referral_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payout_number', sa.String(length=100), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('bank_account_details', sa.JSON(), nullable=True),
    sa.Column('tax_year', sa.String(length=10), nullable=False),
    sa.Column('tax_quarter', sa.String(length=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_payouts_payout_number'), 'referral_payouts', ['payout_number'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('server_status', sa.String(length=50), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('bandwidth_gb', sa.Integer(), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['hosting_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_created', 'servers', ['created_at'], unique=False)
    op.create_index('idx_server_expiry', 'servers', ['expiry_date'], unique=False)
    op.create_index('idx_server_plan', 'servers', ['plan_id'], unique=False)
    op.create_index('idx_server_status', 'servers', ['server_status'], unique=False)
    op.create_index('idx_server_user_status', 'servers', ['user_id', 'server_status'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('login_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_comprehensive', 'invoices', ['user_id', 'status', 'payment_status', 'due_date'], unique=False)
    op.create_index('idx_invoice_date_status', 'invoices', ['invoice_date', 'status'], unique=False)
    op.create_index('idx_invoice_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('idx_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('idx_invoice_order', 'invoices', ['order_id'], unique=False)
    op.create_index('idx_invoice_overdue', 'invoices', ['due_date', 'payment_status'], unique=False)
    op.create_index('idx_invoice_payment_date', 'invoices', ['payment_date'], unique=False)
    op.create_index('idx_invoice_payment_status_balance', 'invoices', ['payment_status', 'balance_due'], unique=False)
    op.create_index('idx_invoice_status_due_date', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index('idx_invoice_user_payment_status', 'invoices', ['user_id', 'payment_status'], unique=False)
    op.create_index('idx_invoice_user_status', 'invoices', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'SERVER', name='paymenttype'), nullable=False),
    sa.Column('activation_type', sa.Enum('DIRECT', 'REFERRAL', name='activationtype'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('payment_status', sa.Enum('INITIATED', 'PENDING', 'PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('commission_distributed', sa.Boolean(), nullable=False),
    sa.Column('commission_distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('razorpay_refund_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_activation', 'payment_transactions', ['activation_type', 'payment_type'], unique=False)
    op.create_index('idx_payment_commission', 'payment_transactions', ['commission_distributed', 'payment_status'], unique=False)
    op.create_index('idx_payment_status_created', 'payment_transactions', ['payment_status', 'created_at'], unique=False)
    op.create_index('idx_payment_user_status', 'payment_transactions', ['user_id', 'payment_status'], unique=False)
    op.create_index('idx_payment_user_type', 'payment_transactions', ['user_id', 'payment_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_activation_type'), 'payment_transactions', ['activation_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_commission_distributed'), 'payment_transactions', ['commission_distributed'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_status'), 'payment_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_type'), 'payment_transactions', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_razorpay_order_id'), 'payment_transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_razorpay_payment_id'), 'payment_transactions', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('referral_earnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_earnings')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_razorpay_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_razorpay_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_commission_distributed'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_activation_type'), table_name='payment_transactions')
    op.drop_index('idx_payment_user_type', table_name='payment_transactions')
    op.drop_index('idx_payment_user_status', table_name='payment_transactions')
    op.drop_index('idx_payment_status_created', table_name='payment_transactions')
    op.drop_index('idx_payment_commission', table_name='payment_transactions')
    op.drop_index('idx_payment_activation', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('idx_invoice_user_status', table_name='invoices')
    op.drop_index('idx_invoice_user_payment_status', table_name='invoices')
    op.drop_index('idx_invoice_status_due_date', table_name='invoices')
    op.drop_index('idx_invoice_payment_status_balance', table_name='invoices')
    op.drop_index('idx_invoice_payment_date', table_name='invoices')
    op.drop_index('idx_invoice_overdue', table_name='invoices')
    op.drop_index('idx_invoice_order', table_name='invoices')
    op.drop_index('idx_invoice_number', table_name='invoices')
    op.drop_index('idx_invoice_due_date', table_name='invoices')
    op.drop_index('idx_invoice_date_status', table_name='invoices')
    op.drop_index('idx_invoice_comprehensive', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('idx_server_user_status', table_name='servers')
    op.drop_index('idx_server_status', table_name='servers')
    op.drop_index('idx_server_plan', table_name='servers')
    op.drop_index('idx_server_expiry', table_name='servers')
    op.drop_index('idx_server_created', table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_referral_payouts_payout_number'), table_name='referral_payouts')
    op.drop_table('referral_payouts')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_plan_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index('idx_order_user_status', table_name='orders')
    op.drop_index('idx_order_user_payment_status', table_name='orders')
    op.drop_index('idx_order_status_payment', table_name='orders')
    op.drop_index('idx_order_service_dates', table_name='orders')
    op.drop_index('idx_order_plan', table_name='orders')
    op.drop_index('idx_order_payment_status_date', table_name='orders')
    op.drop_index('idx_order_payment_date', table_name='orders')
    op.drop_index('idx_order_number', table_name='orders')
    op.drop_index('idx_order_created_date', table_name='orders')
    op.drop_index('idx_order_comprehensive', table_name='orders')
    op.drop_index('idx_order_billing_cycle', table_name='orders')
    op.drop_table('orders')
    op.drop_table('billing_settings')
    op.drop_index(op.f('ix_users_profiles_referral_code'), table_name='users_profiles')
    op.drop_index(op.f('ix_users_profiles_email'), table_name='users_profiles')
    op.drop_index('idx_user_subscription', table_name='users_profiles')
    op.drop_index('idx_user_status_role', table_name='users_profiles')
    op.drop_index('idx_user_referred_by', table_name='users_profiles')
    op.drop_index('idx_user_referral_code', table_name='users_profiles')
    op.drop_index('idx_user_email', table_name='users_profiles')
    op.drop_index('idx_user_created_at', table_name='users_profiles')
    op.drop_index('idx_user_balance_status', table_name='users_profiles')
    op.drop_table('users_profiles')
    op.drop_index(op.f('ix_referral_commission_rates_payment_type'), table_name='referral_commission_rates')
    op.drop_index(op.f('ix_referral_commission_rates_level'), table_name='referral_commission_rates')
    op.drop_index('idx_commission_rate_active', table_name='referral_commission_rates')
    op.drop_table('referral_commission_rates')
    op.drop_index('idx_plan_type_status', table_name='hosting_plans')
    op.drop_index('idx_plan_price', table_name='hosting_plans')
    op.drop_index('idx_plan_created', table_name='hosting_plans')
    op.drop_index('idx_plan_active_featured', table_name='hosting_plans')
    op.drop_table('hosting_plans')
    # ### end Alembic commands ###
