"""Add order_addons and order_services tables with proper relationships

Revision ID: 31a4000cff9a
Revises: 04eab5e04b37
Create Date: 2025-11-15 18:12:42.426183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a4000cff9a'
down_revision: Union[str, None] = '04eab5e04b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
