"""add_billing_address_fields

Revision ID: 34e09dd9aec1
Revises: add_ticket_messages
Create Date: 2025-11-15 00:26:04.925010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e09dd9aec1'
down_revision: Union[str, None] = 'add_ticket_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_cycle_discounts')
    op.drop_table('hosting_plan_configurations')
    op.drop_table('plan_type_metadata')
    op.drop_table('calculator_configurations')
    op.drop_table('ticket_messages')
    op.drop_table('calculator_addon_pricing')
    op.add_column('billing_settings', sa.Column('street', sa.String(length=500), nullable=True))
    op.add_column('billing_settings', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('billing_settings', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('billing_settings', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('billing_settings', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('billing_settings', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('billing_settings', sa.Column('billing_phone', sa.String(length=50), nullable=True))
    op.add_column('billing_settings', sa.Column('invoice_delivery', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_settings', 'invoice_delivery')
    op.drop_column('billing_settings', 'billing_phone')
    op.drop_column('billing_settings', 'billing_email')
    op.drop_column('billing_settings', 'postal_code')
    op.drop_column('billing_settings', 'country')
    op.drop_column('billing_settings', 'state')
    op.drop_column('billing_settings', 'city')
    op.drop_column('billing_settings', 'street')
    op.create_table('calculator_addon_pricing',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('addon_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculator_addon_pricing_pkey')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_internal_note', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_staff_reply', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name='ticket_messages_ticket_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], name='ticket_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_messages_pkey')
    )
    op.create_table('calculator_configurations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vcpu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculator_configurations_pkey')
    )
    op.create_table('plan_type_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('use_case_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('use_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plan_type_metadata_pkey'),
    sa.UniqueConstraint('plan_type', name='plan_type_metadata_plan_type_key')
    )
    op.create_table('hosting_plan_configurations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vcpu', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bandwidth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_quarterly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_semiannually', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_annually', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_biennially', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_triennially', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processor_info', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hosting_plan_configurations_pkey')
    )
    op.create_table('billing_cycle_discounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cycle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='billing_cycle_discounts_pkey'),
    sa.UniqueConstraint('cycle_name', name='billing_cycle_discounts_cycle_name_key')
    )
    # ### end Alembic commands ###
