"""add_role_based_access_control

Revision ID: b3f23f211578
Revises: countries_v1
Create Date: 2025-11-15 00:59:27.887668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f23f211578'
down_revision: Union[str, None] = 'countries_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.alter_column('countries', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_constraint('countries_alpha3_code_key', 'countries', type_='unique')
    op.drop_constraint('countries_code_key', 'countries', type_='unique')
    op.drop_index('idx_countries_active', table_name='countries')
    op.drop_index('idx_countries_code', table_name='countries')
    op.drop_index('idx_countries_name', table_name='countries')
    op.create_index('idx_country_active', 'countries', ['is_active'], unique=False)
    op.create_index('idx_country_code', 'countries', ['code'], unique=False)
    op.create_index('idx_country_name', 'countries', ['name'], unique=False)
    op.create_index('idx_country_search', 'countries', ['name', 'code', 'alpha3_code'], unique=False)
    op.create_index(op.f('ix_countries_alpha3_code'), 'countries', ['alpha3_code'], unique=False)
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_unique_constraint(None, 'countries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_alpha3_code'), table_name='countries')
    op.drop_index('idx_country_search', table_name='countries')
    op.drop_index('idx_country_name', table_name='countries')
    op.drop_index('idx_country_code', table_name='countries')
    op.drop_index('idx_country_active', table_name='countries')
    op.create_index('idx_countries_name', 'countries', ['name'], unique=False)
    op.create_index('idx_countries_code', 'countries', ['code'], unique=False)
    op.create_index('idx_countries_active', 'countries', ['is_active'], unique=False)
    op.create_unique_constraint('countries_code_key', 'countries', ['code'])
    op.create_unique_constraint('countries_alpha3_code_key', 'countries', ['alpha3_code'])
    op.alter_column('countries', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('countries', 'code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###
