"""add_status_to_ticket_attachments

Revision ID: ca34e022749e
Revises: 4d5ae52d85f8
Create Date: 2025-11-15 02:51:02.768254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca34e022749e'
down_revision: Union[str, None] = '4d5ae52d85f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_attachments_id', table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_extension', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('encryption_key_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_safe', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scan_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('scan_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('downloaded_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_downloaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], name='ticket_attachments_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name='ticket_attachments_ticket_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], name='ticket_attachments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_attachments_pkey')
    )
    op.create_index('ix_ticket_attachments_id', 'ticket_attachments', ['id'], unique=False)
    # ### end Alembic commands ###
