"""add_affiliate_referral_system

Revision ID: d8ab01cb89a3
Revises: b3f23f211578
Create Date: 2025-11-15 00:59:51.966059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ab01cb89a3'
down_revision: Union[str, None] = 'b3f23f211578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
