"""
Seed pricing data from static frontend to database
This populates hosting_plans table with all current pricing
"""
import asyncio
import asyncpg
import json

async def seed_pricing_data():
    conn = await asyncpg.connect(
        user='postgres',
        password='hardik123',
        database='ramaera_hosting',
        host='localhost',
        port=5432
    )
    
    print("🔄 Seeding pricing data...")
    
    # Clear existing plans
    await conn.execute("DELETE FROM hosting_plans")
    print("✅ Cleared existing plans")
    
    # General Purpose VM Plans
    general_purpose_plans = [
        {
            'name': 'G.4GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 2,
            'ram_gb': 4,
            'storage_gb': 80,
            'bandwidth_gb': 1000,
            'base_price': 1120,
            'monthly_price': 1120,
            'quarterly_price': 3360,
            'semiannually_price': 6720,
            'annual_price': 13440,
            'biennial_price': 26880,
            'triennial_price': 40320,
            'is_featured': False,
        },
        {
            'name': 'G.8GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 4,
            'ram_gb': 8,
            'storage_gb': 160,
            'bandwidth_gb': 1000,
            'base_price': 2240,
            'monthly_price': 2240,
            'quarterly_price': 6720,
            'semiannually_price': 13440,
            'annual_price': 26880,
            'biennial_price': 53760,
            'triennial_price': 80640,
            'is_featured': True,
        },
        {
            'name': 'G.16GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 6,
            'ram_gb': 16,
            'storage_gb': 320,
            'bandwidth_gb': 1000,
            'base_price': 4080,
            'monthly_price': 4080,
            'quarterly_price': 12240,
            'semiannually_price': 24480,
            'annual_price': 48960,
            'biennial_price': 97920,
            'triennial_price': 146880,
            'is_featured': False,
        },
        {
            'name': 'G.32GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 8,
            'ram_gb': 32,
            'storage_gb': 480,
            'bandwidth_gb': 1000,
            'base_price': 6720,
            'monthly_price': 6720,
            'quarterly_price': 20160,
            'semiannually_price': 40320,
            'annual_price': 80640,
            'biennial_price': 161280,
            'triennial_price': 241920,
            'is_featured': False,
        },
        {
            'name': 'G.48GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 10,
            'ram_gb': 48,
            'storage_gb': 512,
            'bandwidth_gb': 1000,
            'base_price': 8848,
            'monthly_price': 8848,
            'quarterly_price': 26544,
            'semiannually_price': 53088,
            'annual_price': 106176,
            'biennial_price': 212352,
            'triennial_price': 318528,
            'is_featured': False,
        },
        {
            'name': 'G.64GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 12,
            'ram_gb': 64,
            'storage_gb': 640,
            'bandwidth_gb': 1000,
            'base_price': 11360,
            'monthly_price': 11360,
            'quarterly_price': 34080,
            'semiannually_price': 68160,
            'annual_price': 136320,
            'biennial_price': 272640,
            'triennial_price': 408960,
            'is_featured': False,
        },
        {
            'name': 'G.96GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 16,
            'ram_gb': 96,
            'storage_gb': 740,
            'bandwidth_gb': 1000,
            'base_price': 15760,
            'monthly_price': 15760,
            'quarterly_price': 47280,
            'semiannually_price': 94560,
            'annual_price': 189120,
            'biennial_price': 378240,
            'triennial_price': 567360,
            'is_featured': False,
        },
        {
            'name': 'G.128GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 16,
            'ram_gb': 128,
            'storage_gb': 840,
            'bandwidth_gb': 1000,
            'base_price': 19360,
            'monthly_price': 19360,
            'quarterly_price': 58080,
            'semiannually_price': 116160,
            'annual_price': 232320,
            'biennial_price': 464640,
            'triennial_price': 696960,
            'is_featured': False,
        },
        {
            'name': 'G.256GB',
            'plan_type': 'general_purpose',
            'cpu_cores': 24,
            'ram_gb': 256,
            'storage_gb': 1280,
            'bandwidth_gb': 1000,
            'base_price': 35520,
            'monthly_price': 35520,
            'quarterly_price': 106560,
            'semiannually_price': 213120,
            'annual_price': 426240,
            'biennial_price': 852480,
            'triennial_price': 1278720,
            'is_featured': False,
        },
    ]
    
    # CPU Optimized VM Plans
    cpu_optimized_plans = [
        {
            'name': 'C.4GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 2,
            'ram_gb': 4,
            'storage_gb': 80,
            'bandwidth_gb': 1000,
            'base_price': 1520,
            'monthly_price': 1520,
            'quarterly_price': 4560,
            'semiannually_price': 9120,
            'annual_price': 18240,
            'biennial_price': 36480,
            'triennial_price': 54720,
            'is_featured': False,
        },
        {
            'name': 'C.8GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 4,
            'ram_gb': 8,
            'storage_gb': 160,
            'bandwidth_gb': 1000,
            'base_price': 3040,
            'monthly_price': 3040,
            'quarterly_price': 9120,
            'semiannually_price': 18240,
            'annual_price': 36480,
            'biennial_price': 72960,
            'triennial_price': 109440,
            'is_featured': True,
        },
        {
            'name': 'C.16GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 6,
            'ram_gb': 16,
            'storage_gb': 320,
            'bandwidth_gb': 1000,
            'base_price': 5280,
            'monthly_price': 5280,
            'quarterly_price': 15840,
            'semiannually_price': 31680,
            'annual_price': 63360,
            'biennial_price': 126720,
            'triennial_price': 190080,
            'is_featured': False,
        },
        {
            'name': 'C.32GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 8,
            'ram_gb': 32,
            'storage_gb': 480,
            'bandwidth_gb': 1000,
            'base_price': 8320,
            'monthly_price': 8320,
            'quarterly_price': 24960,
            'semiannually_price': 49920,
            'annual_price': 99840,
            'biennial_price': 199680,
            'triennial_price': 299520,
            'is_featured': False,
        },
        {
            'name': 'C.48GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 10,
            'ram_gb': 48,
            'storage_gb': 512,
            'bandwidth_gb': 1000,
            'base_price': 10848,
            'monthly_price': 10848,
            'quarterly_price': 32544,
            'semiannually_price': 65088,
            'annual_price': 130176,
            'biennial_price': 260352,
            'triennial_price': 390528,
            'is_featured': False,
        },
        {
            'name': 'C.64GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 12,
            'ram_gb': 64,
            'storage_gb': 640,
            'bandwidth_gb': 1000,
            'base_price': 13760,
            'monthly_price': 13760,
            'quarterly_price': 41280,
            'semiannually_price': 82560,
            'annual_price': 165120,
            'biennial_price': 330240,
            'triennial_price': 495360,
            'is_featured': False,
        },
        {
            'name': 'C.96GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 16,
            'ram_gb': 96,
            'storage_gb': 740,
            'bandwidth_gb': 1000,
            'base_price': 18960,
            'monthly_price': 18960,
            'quarterly_price': 56880,
            'semiannually_price': 113760,
            'annual_price': 227520,
            'biennial_price': 455040,
            'triennial_price': 682560,
            'is_featured': False,
        },
        {
            'name': 'C.128GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 16,
            'ram_gb': 128,
            'storage_gb': 840,
            'bandwidth_gb': 1000,
            'base_price': 22560,
            'monthly_price': 22560,
            'quarterly_price': 67680,
            'semiannually_price': 135360,
            'annual_price': 270720,
            'biennial_price': 541440,
            'triennial_price': 812160,
            'is_featured': False,
        },
        {
            'name': 'C.256GB',
            'plan_type': 'cpu_optimized',
            'cpu_cores': 24,
            'ram_gb': 256,
            'storage_gb': 1280,
            'bandwidth_gb': 1000,
            'base_price': 40320,
            'monthly_price': 40320,
            'quarterly_price': 120960,
            'semiannually_price': 241920,
            'annual_price': 483840,
            'biennial_price': 967680,
            'triennial_price': 1451520,
            'is_featured': False,
        },
    ]
    
    # Memory Optimized VM Plans
    memory_optimized_plans = [
        {
            'name': 'M.8GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 1,
            'ram_gb': 8,
            'storage_gb': 80,
            'bandwidth_gb': 1000,
            'base_price': 1320,
            'monthly_price': 1320,
            'quarterly_price': 3960,
            'semiannually_price': 7920,
            'annual_price': 15840,
            'biennial_price': 31680,
            'triennial_price': 47520,
            'is_featured': False,
        },
        {
            'name': 'M.16GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 2,
            'ram_gb': 16,
            'storage_gb': 160,
            'bandwidth_gb': 1000,
            'base_price': 2640,
            'monthly_price': 2640,
            'quarterly_price': 7920,
            'semiannually_price': 15840,
            'annual_price': 31680,
            'biennial_price': 63360,
            'triennial_price': 95040,
            'is_featured': True,
        },
        {
            'name': 'M.32GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 4,
            'ram_gb': 32,
            'storage_gb': 320,
            'bandwidth_gb': 1000,
            'base_price': 5280,
            'monthly_price': 5280,
            'quarterly_price': 15840,
            'semiannually_price': 31680,
            'annual_price': 63360,
            'biennial_price': 126720,
            'triennial_price': 190080,
            'is_featured': False,
        },
        {
            'name': 'M.64GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 6,
            'ram_gb': 64,
            'storage_gb': 480,
            'bandwidth_gb': 1000,
            'base_price': 9520,
            'monthly_price': 9520,
            'quarterly_price': 28560,
            'semiannually_price': 57120,
            'annual_price': 114240,
            'biennial_price': 228480,
            'triennial_price': 342720,
            'is_featured': False,
        },
        {
            'name': 'M.96GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 8,
            'ram_gb': 96,
            'storage_gb': 512,
            'bandwidth_gb': 1000,
            'base_price': 13248,
            'monthly_price': 13248,
            'quarterly_price': 39744,
            'semiannually_price': 79488,
            'annual_price': 158976,
            'biennial_price': 317952,
            'triennial_price': 476928,
            'is_featured': False,
        },
        {
            'name': 'M.128GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 10,
            'ram_gb': 128,
            'storage_gb': 640,
            'bandwidth_gb': 1000,
            'base_price': 17360,
            'monthly_price': 17360,
            'quarterly_price': 52080,
            'semiannually_price': 104160,
            'annual_price': 208320,
            'biennial_price': 416640,
            'triennial_price': 624960,
            'is_featured': False,
        },
        {
            'name': 'M.192GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 12,
            'ram_gb': 192,
            'storage_gb': 740,
            'bandwidth_gb': 1000,
            'base_price': 24560,
            'monthly_price': 24560,
            'quarterly_price': 73680,
            'semiannually_price': 147360,
            'annual_price': 294720,
            'biennial_price': 589440,
            'triennial_price': 884160,
            'is_featured': False,
        },
        {
            'name': 'M.256GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 16,
            'ram_gb': 256,
            'storage_gb': 840,
            'bandwidth_gb': 1000,
            'base_price': 32160,
            'monthly_price': 32160,
            'quarterly_price': 96480,
            'semiannually_price': 192960,
            'annual_price': 385920,
            'biennial_price': 771840,
            'triennial_price': 1157760,
            'is_featured': False,
        },
        {
            'name': 'M.384GB',
            'plan_type': 'memory_optimized',
            'cpu_cores': 24,
            'ram_gb': 384,
            'storage_gb': 1280,
            'bandwidth_gb': 1000,
            'base_price': 48320,
            'monthly_price': 48320,
            'quarterly_price': 144960,
            'semiannually_price': 289920,
            'annual_price': 579840,
            'biennial_price': 1159680,
            'triennial_price': 1739520,
            'is_featured': False,
        },
    ]
    
    all_plans = general_purpose_plans + cpu_optimized_plans + memory_optimized_plans
    
    # Insert all plans
    for plan in all_plans:
        features = [
            f"{plan['cpu_cores']} vCPU",
            f"{plan['ram_gb']}GB RAM",
            f"{plan['storage_gb']}GB SSD Storage",
            f"{plan['bandwidth_gb']}GB Bandwidth",
            "IPv4 Address",
            "Console Access",
            "Full Root Access"
        ]
        
        if 'cpu_optimized' in plan['plan_type']:
            features[0] = f"{plan['cpu_cores']} Dedicated vCPU"
            features.append("Intel® Xeon® Gold")
        
        if 'memory_optimized' in plan['plan_type']:
            features.append("High Memory Ratio")
        
        await conn.execute('''
            INSERT INTO hosting_plans (
                name, plan_type, cpu_cores, ram_gb, storage_gb, bandwidth_gb,
                base_price, monthly_price, quarterly_price, annual_price, 
                biennial_price, triennial_price, is_active, is_featured, features,
                description
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15::jsonb, $16)
        ''', 
            plan['name'],
            plan['plan_type'],
            plan['cpu_cores'],
            plan['ram_gb'],
            plan['storage_gb'],
            plan['bandwidth_gb'],
            plan['base_price'],
            plan['monthly_price'],
            plan['quarterly_price'],
            plan['annual_price'],
            plan['biennial_price'],
            plan['triennial_price'],
            True,  # is_active
            plan['is_featured'],
            json.dumps(features),  # Convert to JSON string
            f"{plan['name']} - {plan['plan_type'].replace('_', ' ').title()}"
        )
    
    print(f"✅ Inserted {len(all_plans)} hosting plans")
    
    # Verify data
    count = await conn.fetchval("SELECT COUNT(*) FROM hosting_plans")
    print(f"\n📊 Total plans in database: {count}")
    
    # Show sample
    sample = await conn.fetch("SELECT name, plan_type, monthly_price FROM hosting_plans LIMIT 5")
    print("\n📋 Sample plans:")
    for row in sample:
        print(f"  - {row['name']} ({row['plan_type']}): ₹{row['monthly_price']}/month")
    
    await conn.close()
    print("\n✅ Pricing data seeding complete!")

if __name__ == "__main__":
    asyncio.run(seed_pricing_data())
